force-app/main/default/objects/Incident__c/Incident__c.object-meta.xml
<CustomObject>
    <description>Represents an incident that happened to the company&#39;s systems at a certain date, and its status. The updates are held in a separate object.</description>
    <label>Incident</label>
    <nameField>
        <displayFormat>Incident #{0000}</displayFormat>
        <label>Incident #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Incident&#39;s initial description.</description>
    <inlineHelpText>Incident&#39;s initial description.</inlineHelpText>
    <label>Description</label>
    <length>40000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/IncidentStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>IncidentStartDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>When this incident happened.</description>
    <inlineHelpText>When this incident happened.</inlineHelpText>
    <label>Date/time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of this incident.</description>
    <inlineHelpText>Current status of this incident.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncidentStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <description>System which is affected by this issue.</description>
    <inlineHelpText>System which is affected by this issue.</inlineHelpText>
    <label>System</label>
    <referenceTo>System__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IncidentUpdate__c/IncidentUpdate__c.object-meta.xml
<CustomObject>
    <description>Updates related to an incident. Ideally you should post new status updates every hour or so, depending on the SLA with your customers. They want to know what you are doing to restore the service!</description>
    <label>Incident update</label>
    <nameField>
        <displayFormat>Update {000000}</displayFormat>
        <label>Incident update number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IncidentUpdate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of what this update is about. If the update is to inform that the system has returned to normal, and the incident has been taken care of, then you can use the checkbox &quot;is resolution&quot; to close the issue.</description>
    <inlineHelpText>Description of what this update is about. If the update is to inform that the system has returned to normal, and the incident has been taken care of, then you can use the checkbox &quot;is resolution&quot; to close the issue.</inlineHelpText>
    <label>Description</label>
    <length>40000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/IncidentUpdate__c/fields/Incident__c.field-meta.xml
<CustomField>
    <fullName>Incident__c</fullName>
    <description>Parent incident which this update refers to.</description>
    <inlineHelpText>Parent incident which this update refers to.</inlineHelpText>
    <label>Incident</label>
    <referenceTo>Incident__c</referenceTo>
    <relationshipLabel>Incident updates</relationshipLabel>
    <relationshipName>IncidentUpdates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IncidentUpdate__c/fields/IncidentStatusUpdate__c.field-meta.xml
<CustomField>
    <fullName>IncidentStatusUpdate__c</fullName>
    <description>Select the new status for the related incident, if applicable. For example: if this update is about the resolution, then the incident&#39;s status could be &quot;monitoring&quot; or &quot;resolved&quot;.</description>
    <inlineHelpText>Select the new status for the related incident, if applicable. For example: if this update is about the resolution, then the incident&#39;s status could be &quot;monitoring&quot; or &quot;resolved&quot;.</inlineHelpText>
    <label>New incident status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncidentStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IncidentUpdate__c/fields/SystemStatusUpdate__c.field-meta.xml
<CustomField>
    <fullName>SystemStatusUpdate__c</fullName>
    <description>Select the new status for the related system, if applicable. For example: if this update is about the resolution, then select the appropriate system status.</description>
    <inlineHelpText>Select the new status for the related system, if applicable. For example: if this update is about the resolution, then select the appropriate system status.</inlineHelpText>
    <label>New system status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SystemStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/System__c/System__c.object-meta.xml
<CustomObject>
    <description>Represents a system for the status page report.</description>
    <label>System</label>
    <nameField>
        <label>System name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of this system.</description>
    <inlineHelpText>Current status of this system.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SystemStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/IncidentStatuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INVESTIGATING</fullName>
        <default>true</default>
        <label>Investigating</label>
    </customValue>
    <customValue>
        <fullName>IDENTIFIED</fullName>
        <label>Identified</label>
    </customValue>
    <customValue>
        <fullName>MONITORING</fullName>
        <label>Monitoring</label>
    </customValue>
    <customValue>
        <fullName>RESOLVED</fullName>
        <label>Resolved</label>
    </customValue>
    <description>Available statuses for an incident.</description>
    <masterLabel>Incident statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SystemStatuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UNAVAILABLE</fullName>
        <default>true</default>
        <label>Unavailable</label>
    </customValue>
    <customValue>
        <fullName>PERFORMANCE_DEGRADATION</fullName>
        <label>Performance degradation</label>
    </customValue>
    <customValue>
        <fullName>OPERATIONAL</fullName>
        <label>Operational</label>
    </customValue>
    <description>Available statuses for the system.</description>
    <masterLabel>System statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IncidentUpdateTest.cls
@IsTest
private class IncidentUpdateTest {

    @IsTest
    static void testIncidentTrigger() {
        System__c sys = new System__c(
            Name = 'The Sys',
            Status__c = 'UNAVAILABLE'
        );
        insert sys;

        Incident__c incident = new Incident__c(
            System__c = sys.Id,
            IncidentStartDateTime__c = Datetime.now().addHours(-2),
            Description__c = '<p>Lorem ipsum.</p>',
            Status__c = 'INVESTIGATING'
        );
        insert incident;

        IncidentUpdate__c incidentUpdate = new IncidentUpdate__c(
            Incident__c = incident.Id,
            Description__c = '<p>This closes the incident. All is green!</p>',
            IncidentStatusUpdate__c = 'RESOLVED',
            SystemStatusUpdate__c = 'OPERATIONAL'
        );

        Test.startTest();
        insert incidentUpdate;
        Test.stopTest();

        incident = [SELECT Id, System__r.Status__c, Status__c FROM Incident__c WHERE Id = :incident.Id];

        System.assertEquals(incident.Status__c, 'RESOLVED', 'Should have updated the incident status to "resolved"!');
        System.assertEquals(incident.System__r.Status__c, 'OPERATIONAL', 'Should have updated the system status to "operational".');
    }
}