force-app/main/default/objects/Incident__c/Incident__c.object-meta.xml
<CustomObject>
    <description>Represents an incident that happened to the company&#39;s systems at a certain date, and its status. The updates are held in a separate object.</description>
    <label>Incident</label>
    <nameField>
        <displayFormat>Incident #{0000}</displayFormat>
        <label>Incident #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Incident&#39;s initial description.</description>
    <inlineHelpText>Incident&#39;s initial description.</inlineHelpText>
    <label>Description</label>
    <length>40000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/IncidentStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>IncidentStartDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>When this incident happened.</description>
    <inlineHelpText>When this incident happened.</inlineHelpText>
    <label>Date/time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of this incident.</description>
    <inlineHelpText>Current status of this incident.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IncidentStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <description>System which is affected by this issue.</description>
    <inlineHelpText>System which is affected by this issue.</inlineHelpText>
    <label>System</label>
    <referenceTo>System__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/System__c/System__c.object-meta.xml
<CustomObject>
    <description>Represents a system for the status page report.</description>
    <label>System</label>
    <nameField>
        <label>System name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of this system.</description>
    <inlineHelpText>Current status of this system.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SystemStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/IncidentStatuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INVESTIGATING</fullName>
        <default>true</default>
        <label>Investigating</label>
    </customValue>
    <customValue>
        <fullName>IDENTIFIED</fullName>
        <label>Identified</label>
    </customValue>
    <customValue>
        <fullName>MONITORING</fullName>
        <label>Monitoring</label>
    </customValue>
    <customValue>
        <fullName>RESOLVED</fullName>
        <label>Resolved</label>
    </customValue>
    <description>Available statuses for an incident.</description>
    <masterLabel>Incident statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SystemStatuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>UNAVAILABLE</fullName>
        <default>true</default>
        <label>Unavailable</label>
    </customValue>
    <customValue>
        <fullName>PERFORMANCE_DEGRADATION</fullName>
        <label>Performance degradation</label>
    </customValue>
    <customValue>
        <fullName>OPERATIONAL</fullName>
        <label>Operational</label>
    </customValue>
    <description>Available statuses for the system.</description>
    <masterLabel>System statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StatusPageControllerTest.cls
@IsTest
private class StatusPageControllerTest {

    @IsTest
    static void test_getAllSystems() {
        System__c sys = new System__c(
            Name = 'The Sys',
            Status__c = 'UNAVAILABLE'
        );
        insert sys;

        Test.startTest();
        List<System__c> systems = StatusPageController.getAllSystems();
        Test.stopTest();

        System.assertNotEquals(0, systems.size(), 'Should have retrieved the inserted system record.');
    }

    @IsTest
    static void test_getIncident() {
        System__c sys = new System__c(
            Name = 'The Sys',
            Status__c = 'UNAVAILABLE'
        );
        insert sys;

        Incident__c incident = new Incident__c(
            System__c = sys.Id,
            IncidentStartDateTime__c = Datetime.now().addHours(-2),
            Description__c = '<p>Lorem ipsum.</p>',
            Status__c = 'INVESTIGATING'
        );
        insert incident;

        Test.startTest();
        incident = StatusPageController.getIncident(incident.Id);
        Test.stopTest();

        System.assertNotEquals(null, incident, 'Should have retrieved the inserted incident.');
    }
}